
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.0

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'json_schema_converter.gemspec'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma


RSpec/NestedGroups:
  Max: 4

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 5