---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.0
before_install: gem install bundler -v 2.0.1
script:
  - bundle exec rubocop || travis_terminate 1
  - bundle exec bundle-audit || travis_terminate 1
  - bundle exec rspec || travis_terminate 1
